dist: trusty
language: node_js
node_js: "10"

git:
  autocrlf: input

# matrix:
#   fast_finish: true
#   include:
#     - os: linux
    # - os: windows
    # - os: osx

# allow_failures:
#   - os: windows
#   - os: osx

before_install:
  - npm install -g yarn

install:
  - yarn

script:
  # lint first, no point running tests just to fail on lint
  - yarn lint

  # test production build
  - yarn build
  - yarn clean

  # dev build will run as part of `yarn test`
  - yarn test
